# sops configuration for home-manager secrets
# Each machine has its own age key at ~/.config/sops/age/keys.txt
#
# To set up:
# 1. Generate an age key: age-keygen -o ~/.config/sops/age/keys.txt
# 2. Get the public key: age-keygen -y ~/.config/sops/age/keys.txt
# 3. Add your public key below
keys:
  # Desktop/Laptop (x86_64-linux)
  - &homelinux age1km0tqddwtufyufh7pvfegjjjkjkmwq7jva5ullxq229ky4m5w4ms7g5ney
creation_rules:
  # All secrets encrypted to all machines
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - *homelinux
